export const SET_CURRENT_NUMBER = 'SET_CURRENT_NUMBER';
export const INCREASE_CURRENT_NUMBER_BY_ONE = 'INCREASE_CURRENT_NUMBER_BY_ONE';
export const DECREASE_CURRENT_NUMBER_BY_ONE = 'DECREASE_CURRENT_NUMBER_BY_ONE';